### ISSUE TITLE
一个关于 winrar 的建议

### ISSUE THREAD

**Issue by leonsama** [vfilename/vfilename#1]
去年我也有类似的构思（放在U盘里的轻量级版本管理工具），都开始写 py 代码了，可惜弃坑了。没想到现在看到了一个差不多的成品XD
我在介绍里看到，这个软件的解压功能基于winrar。winrar的中国代理商特别恶心，我认为打包一个zip或7z压缩插件而不直接调用 winrar 会更加稳妥一点（并且一些电脑里可能没预装 winrar ）。

**Comment by vfilename** [comment]
收到（抱歉回复晚了）。我个人使用的是WinRAR官网的，不了解中国代理的情况。目前一切正常，不存在恶心状况。暂时不考虑zip/7z，长话短说，就是WinRAR已经满足所有条件。刘志勇

**Comment by vfilename** [comment]
已经支持7z了。刘志勇
